// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for macos - '
            'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvVfrw3cjctK0qYy7nMcCsqMppw8SPeMs',
    appId: '1:182078486211:android:55acccbc838ae31f795476',
    messagingSenderId: '182078486211',
    projectId: 'shopez-f2501',
    storageBucket: 'shopez-f2501.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUZzaMW2dF9jSLZayA1-nee_0jknSa7Rc',
    appId: '1:182078486211:ios:62e9d17c8ba51acc795476',
    messagingSenderId: '182078486211',
    projectId: 'shopez-f2501',
    storageBucket: 'shopez-f2501.firebasestorage.app',
    androidClientId: '182078486211-0l718hd7lugl2i5b20o22f6edl5i6ul7.apps.googleusercontent.com',
    iosClientId: '182078486211-p4me6huqtf93gldjv3vf0120fhh273jo.apps.googleusercontent.com',
    iosBundleId: 'com.shopezy.seller',
  );
}
